name: Create integration tests
on:
  pull_request:
    types: [opened, reopened]

jobs:
  create-integration-tests-check:
    strategy:
      matrix:
        runs-on: [ubuntu-latest]
      fail-fast: false

    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Create button to run integration tests
        uses: octokit/request-action@v2.x
        id: create_check_run
        with:
          route: POST /repos/:repository/check-runs
          repository: ${{ github.repository }}
          mediaType: '{"previews": ["antiope"]}'
          name: "Ensure integration tests"
          head_sha: ${{ github.sha }}
          actions:
            - label: Run integration
              description: Run integration tests
              identifier: integration-action
          output: '{"title":"Test check run title","summary": "A summary of the test check run", "images": [{"alt": "Test image", "image_url": "https://octodex.github.com/images/jetpacktocat.png"}]}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}