name: Create integration tests
on:
  pull_request:
    types: [opened]

jobs:
  create-integration-tests-check:
    strategy:
      matrix:
        runs-on: [ubuntu-latest]
      fail-fast: false

    runs-on: ${{ matrix.runs-on }}
    steps:
      - run: echo "$DATA"
        env:
          DATA: ${{ toJson(github.event) }}