name: Integration tests
on:
  pull_request:
    branches:
      - master

jobs:
  create-integration-tests-check:
    name: Create integration test check
    strategy:
      matrix:
        runs-on: [ubuntu-latest]
      fail-fast: false

    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Create button to run integration tests
        uses: octokit/request-action@v2.x
        id: create_check_run
        with:
          route: POST /repos/${{ github.repository }}/check-runs
          mediaType: '{"previews": ["antiope"]}'
          name: "Integration tests have been run"
          head_sha: ${{ github.event.pull_request.head.sha }}
          status: 'completed'
          conclusion: 'failure'
          output: '{"title":"Integration tests","summary": "When you are ready to merge your pull request, post a comment with \"bot: integration\" to run them and pass the check"}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}