name: Tests
on:
  check_suite:
    types: [rerequested, requested]
    paths-ignore:
      - '**.md'

jobs:
  create-integration-tests-check:
    strategy:
      matrix:
        runs-on: [ubuntu-latest]
      fail-fast: false

    runs-on: ${{ matrix.runs-on }}
    
    steps:
      - name: Create a check for integration tests
        run: echo ${{ toJSON(github) }}
