name: Prepare integration tests
on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'

jobs:
  create-integration-tests-check:
    name: Create integration test check
    strategy:
      matrix:
        runs-on: [ubuntu-latest]
      fail-fast: false

    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Create a check for integration tests
        uses: octokit/request-action@v2.x
        id: create_check_run
        with:
          route: POST /repos/${{ github.repository }}/check-runs
          mediaType: '{"previews": ["antiope"]}'
          name: "Integration tests pass"
          head_sha: ${{ github.event.pull_request.head.sha }}
          status: 'queued'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}