on:
  push:
    branches:
      - master
    paths:
      - '**.md'

name: Create Slate Documentation on Push
jobs:
  action-filter:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Build documentation
        uses: docker://decathlon/slate-builder-action:latest
        env:
          DOC_BASE_FOLDER: ./docs/documentation
          ZIP_BUILD: false
          TEMPLATE_REPO: 'boostercloud/docs-site'
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: ./docs/documentation/build
