name: Mirror
on:
  issue_comment:
    types:
      - created
  

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.5.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |          
            if(context.payload.comment.body.includes('#PUBLISH#')){
              github.pulls.create({
                owner: 'boostercloud',
                repo: 'booster',
                title: context.issue.title,
                head: context.payload.issue.pull_request.head,
                base: context.payload.issue.pull_request.base,
                body: context.payload.issue.pull_request.body
              })
            }
