name: Mirror
on:
  issue_comment:
    types:
      - created
  

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.5.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            (async () => {
              console.log('PULL REQUEST: ', context.payload.issue.pull_request)
              if(context.payload.comment.body.toLower() === 'please publish'){
                await github.pulls.create({
                  owner: 'boostercloud',
                  repo: 'booster',
                  title: context.payload.issue.title,
                  head: context.payload.issue.pull_request.head,
                  base: 'master',
                  body: context.payload.issue.body
                })
              }
            })()
