name: Mirror
on:
  issue_comment:
    types:
      - created
  

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.5.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            console.log('OWNER: ', context.payload.repository.owner)
            var pr = github.pulls.get({
              owner: context.payload.repository.owner.name,
              repo: context.payload.repository.name,
              pull_number: context.payload.issue.number
            })
            console.log('PULL REQUEST: ', pr)
            if(context.payload.comment.body.includes('#PUBLISH#')){
              github.pulls.create({
                owner: 'boostercloud',
                repo: 'booster',
                title: context.payload.issue.title,
                head: pr.head,
                base: pr.base,
                body: context.payload.issue.body
              })
            }
