name: Mirror
on:
  issue_comment:
    types:
      - created
  

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.5.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            console.log('CONTEXT: ', context)
            var comments = context.issue.comments.map(i => i.body)
            if(comments.includes('#PUBLISH#')){
              github.pulls.create({
                owner: 'boostercloud',
                repo: 'booster',
                title: context.issue.title,
                head: context.pull.head,
                base: context.pull.base,
                body: context.pull.body
              })
            }
